default_language_version:
  python: python3.10

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.290
    hooks:
    -   id: ruff
        alias: autoformat
        args: [--fix]
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        exclude: ^.*\b(migrations|manage\.py)\b.*$
