version: "3.8"

services:

  db:
    build:
      context: ./docker/postgres/
      dockerfile: dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./docker/postgres/.env
    container_name: postgres
    restart: unless-stopped

  redis:
    image: redis:7.0.11-alpine
    container_name: redis

  web:
    build:
      context: .
    image: sub365_web
    entrypoint: /home/app/web/docker/web-entrypoint.sh
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    restart: unless-stopped
    container_name: sub365
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3

  celery_worker:
    restart: always
    build:
      context: .
    image: sub365_celery_worker
    entrypoint: /home/app/web/docker/worker-entrypoint.sh
    volumes:
      - .:/home/app/web
    container_name: celery
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - web

  celery_beat:
    restart: always
    build:
      context: .
    image: sub365_celery_beat
    entrypoint: /home/app/web/docker/beat-entrypoint.sh
    volumes:
      - .:/home/app/web
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - web

  flower:
    build:
      context: .
    image: sub365_flower
    entrypoint: /home/app/web/docker/flower-entrypoint.sh
    volumes:
      - .:/home/app/web
    env_file:
      - ./.env
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

  nginx:
    build:
      context: ./docker/nginx/
      dockerfile: dockerfile
    container_name: nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:80
    depends_on:
      - web
    restart: always

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key $${STRIPE_API_KEY} --device-name $${STRIPE_DEVICE_NAME} --forward-to $${STRIPE_FORWARD_TO}"
    env_file:
      - ./.env
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
