[tool.black]
target-version = ["py310"]
line-length = 119
include = '\.pyi?$'
exclude = '''
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
'''

[tool.ruff]
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "I",   # isort
  "DJ",  # flake8-django
  "COM", # flake8-commas
  "N",   # pep8-naming
  "G",   # flake8-logging-format
]

# Avoid enforcing line-length violations (`E501`)
ignore = ["E501"]

# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

# Exclude files and directories.
extend-exclude = ["migrations", "manage.py"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
