# Generated by Django 4.2.1 on 2023-06-22 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="status",
            new_name="subject",
        ),
    ]
