# Generated by Django 4.2.1 on 2023-06-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
