# Generated by Django 4.2.1 on 2023-07-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Active"),
                    ("I", "Inactive"),
                    ("E", "Expired"),
                    ("C", "Canceled"),
                ],
                default="I",
                max_length=1,
            ),
        ),
    ]
