# Generated by Django 4.2.1 on 2023-06-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subdomain',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
