# Generated by Django 4.2.1 on 2023-06-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripeplan",
            name="description",
            field=models.TextField(help_text="300 characters", max_length=300),
        ),
    ]
