# Generated by Django 5.0.7 on 2024-07-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverowner",
            name="avatar",
            field=models.CharField(blank=True, help_text="The ID of the Serverowner's avatar from Discord.", max_length=255, null=True, verbose_name="avatar"),
        ),
    ]
