# Generated by Django 4.2.6 on 2023-10-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinsubscription',
            options={'get_latest_by': ['-created'], 'ordering': ['-created'], 'verbose_name': 'coin subscription', 'verbose_name_plural': 'coin subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='stripesubscription',
            options={'get_latest_by': ['-created'], 'ordering': ['-created'], 'verbose_name': 'stripe subscription', 'verbose_name_plural': 'stripe subscriptions'},
        ),
    ]
