# Generated by Django 4.2.5 on 2023-09-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon of the server on Discord.', max_length=255, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='serverowner',
            name='avatar',
            field=models.CharField(blank=True, help_text="The ID of the Serverowner's avatar from Discord.", max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='serverowner',
            name='coinpayment_api_public_key',
            field=models.CharField(blank=True, help_text='Coinpayment API public key of the serverowner.', max_length=255, null=True, verbose_name='coinpayment api public key'),
        ),
        migrations.AlterField(
            model_name='serverowner',
            name='coinpayment_api_secret_key',
            field=models.CharField(blank=True, help_text='Coinpayment API secret key of the serverowner.', max_length=255, null=True, verbose_name='coinpayment api secret key'),
        ),
        migrations.AlterField(
            model_name='serverowner',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='The stripe account ID of the Serverowner.', max_length=100, null=True, verbose_name='stripe account id'),
        ),
        migrations.AlterField(
            model_name='stripeplan',
            name='permission_description',
            field=models.CharField(blank=True, help_text='Description of permissions to be given to subscribers.', max_length=255, null=True, verbose_name='permission description'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='avatar',
            field=models.CharField(blank=True, help_text='Avatar URL of the subscriber.', max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID of the subscriber.', max_length=255, null=True, verbose_name='stripe customer id'),
        ),
    ]
