# Generated by Django 4.2.1 on 2023-07-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeplan",
            name="discord_role_id",
            field=models.CharField(
                default="", help_text="ID of Discord role to be assigned to subscribers", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stripeplan",
            name="permission_description",
            field=models.TextField(
                blank=True, help_text="Description of permissions to be given to subscribers", null=True
            ),
        ),
    ]
