# Generated by Django 4.2.6 on 2023-10-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='body',
            field=models.TextField(blank=True, help_text='Payment details of the affiliate when registered via Stripe.', max_length=300, verbose_name='payment information'),
        ),
    ]
