# Generated by Django 4.2.1 on 2023-06-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="avatar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
