# Generated by Django 4.2.1 on 2023-06-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_stripeplan_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
