# Generated by Django 4.2.1 on 2023-06-13 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_server_server_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='server_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.serverowner'),
        ),
    ]
