# Generated by Django 4.2.1 on 2023-07-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_stripeplan_discord_role_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripeplan",
            name="permission_description",
            field=models.CharField(
                blank=True,
                help_text="Description of permissions to be given to subscribers",
                max_length=255,
                null=True,
            ),
        ),
    ]
