# Generated by Django 5.0.7 on 2024-07-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_serverowner_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="icon",
            field=models.CharField(blank=True, help_text="Icon of the server on Discord.", max_length=255, null=True, verbose_name="icon"),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="avatar",
            field=models.CharField(blank=True, help_text="Avatar URL of the subscriber.", max_length=255, null=True, verbose_name="avatar"),
        ),
    ]
