# Generated by Django 4.2.1 on 2023-06-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_server_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverowner",
            name="subdomain",
            field=models.CharField(max_length=20),
        ),
    ]
