# Generated by Django 4.2.6 on 2023-10-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_paymentdetail_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discord_id',
        ),
    ]
