# Generated by Django 4.2.6 on 2023-10-09 12:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_coinsubscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The amount in dollars for the plan.', max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='coinplan',
            name='discord_role_id',
            field=models.CharField(help_text='ID of Discord role to be assigned to subscribers.', max_length=255, verbose_name='discord role id'),
        ),
        migrations.AlterField(
            model_name='coinplan',
            name='interval_count',
            field=models.IntegerField(help_text='Number of months the plan should last.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='interval count'),
        ),
        migrations.AlterField(
            model_name='coinplan',
            name='name',
            field=models.CharField(help_text='The name of the plan.', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='coinplan',
            name='permission_description',
            field=models.CharField(blank=True, help_text='Description of permissions to be given to subscribers.', max_length=255, null=True, verbose_name='permission description'),
        ),
        migrations.AlterField(
            model_name='coinplan',
            name='serverowner',
            field=models.ForeignKey(help_text='The serverowner who created the plan.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_plans', to='accounts.serverowner', verbose_name='serverowner'),
        ),
        migrations.AlterField(
            model_name='coinplan',
            name='subscriber_count',
            field=models.IntegerField(default=0, help_text='The number of subscribers to this plan.', verbose_name='subscriber count'),
        ),
        migrations.AlterField(
            model_name='stripeplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The amount in dollars for the plan.', max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='stripeplan',
            name='name',
            field=models.CharField(help_text='The name of the plan.', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='stripeplan',
            name='serverowner',
            field=models.ForeignKey(help_text='The serverowner who created the plan.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_plans', to='accounts.serverowner', verbose_name='serverowner'),
        ),
    ]
