# Generated by Django 4.2.1 on 2023-07-17 23:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_subscription_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriber",
            name="stripe_account_id",
        ),
    ]
