# Generated by Django 4.2.1 on 2023-06-13 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscriber_server_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='server_owner',
            new_name='subscribed_via',
        ),
    ]
