# Generated by Django 4.2.1 on 2023-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_subscriber_stripe_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
