# Generated by Django 4.2.10 on 2024-02-15 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverowner',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total subscription earnings of the Serverowner.', max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total earnings'),
        ),
    ]
