# Generated by Django 4.2.1 on 2023-06-16 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_serverowner_subdomain"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="avatar",
            new_name="icon",
        ),
    ]
