# Generated by Django 4.2.1 on 2023-07-05 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_stripeplan_permission_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverowner",
            name="affiliate_commission",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
    ]
