# Generated by Django 4.2.1 on 2023-06-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_subscriber_stripe_subscription_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriber",
            name="stripe_subscription_id",
        ),
        migrations.AddField(
            model_name="subscription",
            name="customer_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
