# Generated by Django 4.2.1 on 2023-07-22 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_subscriber_stripe_customer_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="customer_id",
        ),
    ]
