# Generated by Django 4.2.1 on 2023-06-18 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_avatar_server_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripeplan",
            name="interval",
        ),
        migrations.AddField(
            model_name="stripeplan",
            name="interval_count",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)],
            ),
            preserve_default=False,
        ),
    ]
