# Generated by Django 4.2.5 on 2023-10-06 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_subscriber_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeplan',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='stripeplan',
            name='user',
        ),
        migrations.AddField(
            model_name='stripeplan',
            name='serverowner',
            field=models.ForeignKey(default=19, help_text='The serverowner who created the plan.', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.serverowner', verbose_name='serverowner'),
            preserve_default=False,
        ),
    ]
