# Generated by Django 4.2.1 on 2023-06-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_subscriber_stripe_subscription_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="session_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
