# Generated by Django 4.2.1 on 2023-07-05 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_serverowner_affiliate_commission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverowner",
            name="affiliate_commission",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
