# Generated by Django 4.2.1 on 2023-06-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_server_owner_subscriber_subscribed_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
