# Generated by Django 4.2.10 on 2024-02-16 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_serverowner_total_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinplan',
            name='subscription_earnings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The total subscription earnings for this plan.', max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subscription earnings'),
        ),
        migrations.AddField(
            model_name='stripeplan',
            name='subscription_earnings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The total subscription earnings for this plan.', max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subscription earnings'),
        ),
    ]
