# Generated by Django 4.2.1 on 2023-06-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_stripeplan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeplan',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
