# Generated by Django 4.2.1 on 2023-07-22 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_subscription_customer_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "get_latest_by": ["-subscription_date"],
                "ordering": ["-subscription_date"],
            },
        ),
    ]
