# Generated by Django 4.2.1 on 2023-06-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_subscription_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
