# Generated by Django 4.2.5 on 2023-10-06 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_stripeplan_currency_remove_stripeplan_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinplan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stripeplan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
