# Generated by Django 4.2.1 on 2023-06-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_stripeplan_interval_stripeplan_interval_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripeplan",
            name="currency",
            field=models.CharField(default="usd", max_length=3),
        ),
    ]
