# Generated by Django 4.2.1 on 2023-07-05 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_serverowner_affiliate_commission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affiliate",
            name="total_invites",
        ),
    ]
