# Generated by Django 5.0.6 on 2024-05-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_coinplan_permission_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinsubscription',
            name='address',
            field=models.CharField(blank=True, default='', help_text='The Litecoin address associated with the subscription.', max_length=225, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='coinsubscription',
            name='checkout_url',
            field=models.CharField(blank=True, default='', help_text='The CoinPayment URL for subscriber redirection.', max_length=225, verbose_name='checkout url'),
        ),
        migrations.AlterField(
            model_name='coinsubscription',
            name='status_url',
            field=models.CharField(blank=True, default='', help_text='The URL for accessing transaction status information.', max_length=225, verbose_name='status url'),
        ),
        migrations.AlterField(
            model_name='coinsubscription',
            name='subscription_id',
            field=models.CharField(blank=True, default='', help_text='The subscription ID associated with this subscription.', max_length=225, verbose_name='subscription id'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='body',
            field=models.TextField(blank=True, default='', help_text='Payment details of the affiliate when registered via Stripe.', max_length=300, verbose_name='payment information'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='litecoin_address',
            field=models.CharField(blank=True, default='', help_text='The Litecoin address of the affiliate, used when registered via CoinPayments.', max_length=255, verbose_name='litecoin address'),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='session_id',
            field=models.CharField(blank=True, default='', help_text='The Stripe checkout session ID associated with this subscription.', max_length=200, verbose_name='session id'),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='subscription_id',
            field=models.CharField(blank=True, default='', help_text='The subscription ID associated with this subscription.', max_length=225, verbose_name='subscription id'),
        ),
    ]
