# Generated by Django 4.2.1 on 2023-07-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_subscription_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="affiliate",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"get_latest_by": ["-created"], "ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="serverowner",
            name="coinbase_api_public_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="serverowner",
            name="coinbase_api_secret_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="serverowner",
            name="coinbase_onboarding",
            field=models.BooleanField(default=False),
        ),
    ]
