# Generated by Django 4.2.1 on 2023-06-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_stripeplan_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeplan",
            name="status",
            field=models.CharField(choices=[("A", "Active"), ("I", "Inactive")], default="A", max_length=1),
        ),
    ]
