# Generated by Django 4.2.1 on 2023-07-07 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_affiliate_total_invites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affiliateinvitee",
            name="paid",
        ),
    ]
