# Generated by Django 4.2.1 on 2023-06-24 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_subscription_expiration_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriber",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="subscriber",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscriber",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
