# Generated by Django 4.2.1 on 2023-06-07 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_subscriber_discord_id_subscriber_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='server_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='accounts.profile'),
        ),
    ]
