# Generated by Django 4.2.1 on 2023-06-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_stripeplan_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripeplan",
            name="description",
            field=models.TextField(help_text="100 characters", max_length=100),
        ),
    ]
