# Generated by Django 4.2.1 on 2023-06-24 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_subscriber_options_subscriber_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="value",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)],
            ),
        ),
    ]
