# Generated by Django 4.2.1 on 2023-07-25 08:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0007_alter_affiliate_options_alter_subscription_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount_dollars", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "amount_litecoin",
                    models.DecimalField(decimal_places=2, max_digits=9),
                ),
                (
                    "interval_count",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="300 characters", max_length=300),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "Active"), ("I", "Inactive")],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("subscriber_count", models.IntegerField(default=0)),
                (
                    "discord_role_id",
                    models.CharField(
                        help_text="ID of Discord role to be assigned to subscribers",
                        max_length=255,
                    ),
                ),
                (
                    "permission_description",
                    models.CharField(
                        blank=True,
                        help_text="Description of permissions to be given to subscribers",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "serverowner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.serverowner",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
