# Generated by Django 4.2.1 on 2023-07-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_affiliateinvitee_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliate",
            name="server_id",
            field=models.CharField(max_length=255),
        ),
    ]
