# Generated by Django 4.2.1 on 2023-06-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_subscription_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="subscription_date",
            field=models.DateTimeField(),
        ),
    ]
