# Generated by Django 4.2.1 on 2023-06-13 03:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'get_latest_by': ['-created']},
        ),
        migrations.AddField(
            model_name='subscription',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
