# Generated by Django 4.2.1 on 2023-06-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_subscriber_server_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.profile'),
        ),
    ]
