# Generated by Django 4.2.1 on 2023-07-09 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_affiliate_server_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliatePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The commission to be paid.",
                        max_digits=9,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        help_text="Discord ID of the Affiliate",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.affiliate",
                    ),
                ),
                (
                    "serverowner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.serverowner",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        help_text="The Affiliate Invitee who subscribed",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.subscriber",
                    ),
                ),
            ],
        ),
    ]
