# Generated by Django 4.2.1 on 2023-07-25 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_coinplan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coinplan",
            old_name="amount_dollars",
            new_name="amount",
        ),
        migrations.RemoveField(
            model_name="coinplan",
            name="amount_litecoin",
        ),
    ]
