# Generated by Django 4.2.1 on 2023-06-30 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_subscription_subscription_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverowner",
            name="affiliate_commission",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="is_affiliate",
            field=models.BooleanField(default=False),
        ),
    ]
