# Generated by Django 4.2.1 on 2023-06-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_subscription_options_subscription_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
