# Generated by Django 4.2.1 on 2023-07-10 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_affiliatepayment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="affiliatepayment",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="affiliate",
            name="last_payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="affiliate",
            name="pending_commissions",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name="affiliate",
            name="total_commissions_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total commissions paid to the affiliate",
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="serverowner",
            name="total_pending_commissions",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total pending commissions to be paid by the server owner",
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
