# Generated by Django 4.2.1 on 2023-07-26 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_rename_amount_dollars_coinplan_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinplan",
            name="serverowner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coin_plans",
                to="accounts.serverowner",
            ),
        ),
    ]
