# Generated by Django 4.2.1 on 2023-06-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_stripeplan_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
