# Generated by Django 4.2.1 on 2023-06-30 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_serverowner_affiliate_commission_user_is_affiliate"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="affiliate_link",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="Affiliate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "subscriber",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="accounts.subscriber"),
                ),
            ],
        ),
    ]
