# Generated by Django 4.2.1 on 2023-06-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_subscription_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
