# Generated by Django 4.2.1 on 2023-07-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_affiliatepayment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliate",
            name="total_invites",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
