# Generated by Django 4.2.1 on 2023-07-26 04:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_coinplan_serverowner"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscription_date", models.DateTimeField()),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("I", "Inactive"),
                            ("E", "Expired"),
                            ("C", "Canceled"),
                        ],
                        default="I",
                        max_length=1,
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.coinplan",
                    ),
                ),
                (
                    "subscribed_via",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.serverowner",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_subscriptions",
                        to="accounts.subscriber",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "get_latest_by": ["-created"],
            },
        ),
    ]
