# Generated by Django 4.2.1 on 2023-07-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_affiliate_total_invites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[("A", "Active"), ("I", "Inactive"), ("E", "Expired")],
                default="I",
                max_length=1,
            ),
        ),
    ]
