# Generated by Django 4.2.1 on 2023-06-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_subscriber_affiliate_link_affiliate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriber",
            name="affiliate_link",
        ),
        migrations.AddField(
            model_name="affiliate",
            name="affiliate_link",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="affiliate",
            name="discord_id",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="affiliate",
            name="server",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
