# Generated by Django 4.2.1 on 2023-06-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_subscription_subscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeplan',
            name='active',
        ),
    ]
