# Generated by Django 4.2.1 on 2023-07-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_coinsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="coinsubscription",
            name="address",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="coinsubscription",
            name="checkout_url",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="coinsubscription",
            name="qrcode_url",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="coinsubscription",
            name="status_url",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="coinsubscription",
            name="subscription_id",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
