# Generated by Django 4.2.1 on 2023-06-30 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_remove_subscriber_affiliate_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="affiliate",
            old_name="server",
            new_name="server_id",
        ),
    ]
