# Generated by Django 4.2.1 on 2023-07-11 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_subscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliatepayment",
            name="date_payment_confirmed",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
