# Generated by Django 4.2.1 on 2023-06-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_stripeplan_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeplan',
            name='subscriber_count',
            field=models.IntegerField(default=0),
        ),
    ]
