# Generated by Django 4.2.1 on 2023-06-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_stripeplan_subscriber_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeplan',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
