# Generated by Django 4.2.1 on 2023-07-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_alter_coinsubscription_subscription_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="coinsubscription",
            name="coin_amount",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
