# Generated by Django 4.2.1 on 2023-06-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_rename_server_affiliate_server_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliate",
            name="total_invites",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
