# Generated by Django 4.2.1 on 2023-07-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_affiliatepayment_date_payment_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliatepayment",
            name="date_payment_confirmed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
