# Generated by Django 4.2.1 on 2023-06-30 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_affiliate_total_invites"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliate",
            name="serverowner",
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to="accounts.serverowner"),
            preserve_default=False,
        ),
    ]
