# Generated by Django 4.2.1 on 2023-07-31 07:20

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_coinsubscription_coin_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliate",
            name="pending_coin_commissions",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="affiliate",
            name="total_coin_commissions_paid",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                help_text="Total coin commissions paid to the affiliate",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="affiliatepayment",
            name="coin_amount",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                help_text="The coin commission to be paid.",
                max_digits=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coinsubscription",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="server",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="server",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="serverowner",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serverowner",
            name="total_coin_pending_commissions",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                help_text="Total pending coin commissions to be paid by the server owner",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="serverowner",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="stripeplan",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="affiliatepayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The dollar commission to be paid.",
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="serverowner",
            name="total_pending_commissions",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total pending dollar commissions to be paid by the server owner",
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscription_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
