# Generated by Django 4.2.1 on 2023-06-14 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_stripeplan_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stripeplan",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="stripeplan",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
