# Generated by Django 4.2.1 on 2023-07-01 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_affiliate_serverowner"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateInvitee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("discord_id", models.CharField(max_length=255, unique=True)),
                ("invitee_id", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("inviter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.affiliate")),
            ],
        ),
    ]
