# Generated by Django 4.2.1 on 2023-07-31 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_affiliate_pending_coin_commissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliatepayment",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The dollar commission to be paid.",
                max_digits=9,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="affiliatepayment",
            name="coin_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="The coin commission to be paid.",
                max_digits=20,
                null=True,
            ),
        ),
    ]
