# Generated by Django 4.2.1 on 2023-07-15 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_paymentdetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affiliate",
            name="total_invites",
        ),
    ]
