# Generated by Django 4.2.1 on 2023-06-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_alter_stripeplan_options_stripeplan_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[("A", "Active"), ("I", "Inactive"), ("C", "Cancelled")], default="A", max_length=1
            ),
        ),
    ]
