# Generated by Django 4.2.1 on 2023-07-01 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_affiliateinvitee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affiliateinvitee",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="affiliateinvitee",
            name="invitee_id",
        ),
    ]
