# Generated by Django 4.2.1 on 2023-07-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_remove_affiliate_total_invites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdetail",
            name="affiliate",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.affiliate"
            ),
        ),
    ]
