# Generated by Django 4.2.1 on 2023-07-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_alter_affiliatepayment_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdetail",
            name="litecoin_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="paymentdetail",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
