# Generated by Django 4.2.1 on 2023-06-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_subscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeplan",
            name="status",
            field=models.CharField(choices=[("A", "Active"), ("I", "Inactive")], default="A", max_length=1),
        ),
    ]
