# Generated by Django 4.2.1 on 2023-07-01 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_remove_affiliateinvitee_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="affiliateinvitee",
            old_name="inviter",
            new_name="affiliate",
        ),
    ]
