# Generated by Django 4.2.1 on 2023-07-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_paymentdetail_litecoin_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinsubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Active"),
                    ("I", "Inactive"),
                    ("E", "Expired"),
                    ("C", "Canceled"),
                    ("F", "Failed"),
                ],
                default="I",
                max_length=1,
            ),
        ),
    ]
