# Generated by Django 4.2.1 on 2023-06-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_alter_stripeplan_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeplan",
            name="product_id",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
