# Generated by Django 4.2.1 on 2023-07-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_rename_inviter_affiliateinvitee_affiliate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affiliateinvitee",
            name="discord_id",
        ),
        migrations.AddField(
            model_name="affiliateinvitee",
            name="invitee_discord_id",
            field=models.CharField(default="", help_text="Discord ID of the Invitee", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="affiliate",
            name="discord_id",
            field=models.CharField(help_text="Discord ID of the Affiliate", max_length=255, unique=True),
        ),
    ]
