# Generated by Django 4.2.1 on 2023-08-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_alter_coinsubscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverowner",
            name="stripe_onboarding",
            field=models.BooleanField(default=False),
        ),
    ]
