# Generated by Django 4.2.1 on 2023-06-15 05:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_stripeplan_product_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stripeplan",
            old_name="plan_id",
            new_name="price_id",
        ),
    ]
