# Generated by Django 4.2.1 on 2023-07-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_remove_affiliateinvitee_discord_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affiliate",
            name="id",
        ),
        migrations.AlterField(
            model_name="affiliate",
            name="discord_id",
            field=models.CharField(
                help_text="Discord ID of the Affiliate", max_length=255, primary_key=True, serialize=False
            ),
        ),
    ]
