# Generated by Django 4.2.1 on 2023-08-03 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_serverowner_stripe_onboarding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serverowner",
            name="stripe_onboarding",
        ),
    ]
