# Generated by Django 4.2.1 on 2023-06-15 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_rename_plan_id_stripeplan_price_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripeplan",
            name="status",
        ),
    ]
