# Generated by Django 4.2.4 on 2023-08-13 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_remove_serverowner_stripe_onboarding"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="affiliateinvitee",
            options={"ordering": ["-id"]},
        ),
    ]
