# Generated by Django 4.2.4 on 2023-08-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_affiliateinvitee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinsubscription',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('E', 'Expired'), ('C', 'Canceled')], default='I', max_length=1),
        ),
    ]
