# Generated by Django 4.2.1 on 2023-06-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_remove_stripeplan_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="subscribed",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(choices=[("A", "Active"), ("I", "Inactive")], default="I", max_length=1),
        ),
    ]
