# Generated by Django 4.2.4 on 2023-08-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_coinsubscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinsubscription',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('E', 'Expired'), ('C', 'Canceled')], default='P', max_length=1),
        ),
    ]
