# Generated by Django 4.2.4 on 2023-08-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_coinsubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='date_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
