# Generated by Django 4.2.4 on 2023-09-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_accesscode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinsubscription',
            name='subscription_id',
            field=models.CharField(blank=True, help_text='The Coinpayments Transaction ID.', max_length=225, null=True, verbose_name='subscription id'),
        ),
    ]
