# Generated by Django 4.2.4 on 2023-09-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_coinsubscription_subscription_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['-created'], 'verbose_name': 'discord server', 'verbose_name_plural': 'discord servers'},
        ),
    ]
