# Generated by Django 4.2.4 on 2023-09-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_server_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverowner',
            name='stripe_onboarding',
            field=models.BooleanField(default=False, help_text='If this Serverowner onboarded via stripe.', verbose_name='stripe onboarding'),
        ),
    ]
