# Dockerfile for NGINX image
FROM nginx:1.23-alpine

# Copy server configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# RUN rm /etc/nginx/conf.d/default.conf
# COPY nginx.conf /etc/nginx/conf.d
