FROM nginx:1.25

# Inside nginx/default.conf
# COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
# COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf