name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SECRET_KEY: "django-invalid"
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost"
      SQL_ENGINE: "django.db.backends.sqlite3"
      SQL_DATABASE: "db.sqlite3"
      SQL_USER: ""
      SQL_PASSWORD: ""
      SQL_HOST: ""
      SQL_PORT: ""
      DISCORD_CLIENT_ID: ""
      DISCORD_CLIENT_SECRET: ""
      STRIPE_PUBLIC_KEY: ""
      STRIPE_API_KEY: ""
      STRIPE_WEBHOOK_SECRET: ""
      EMAIL_BACKEND: ""
      EMAIL_HOST: ""
      EMAIL_HOST_USER: ""
      EMAIL_HOST_PASSWORD: ""
      EMAIL_PORT: 1
      DEFAULT_EMAIL: ""
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_STORAGE_BUCKET_NAME: ""
      SENTRY: ""
      CELERY_BROKER_URL: ""

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test accounts/tests/
